{
    'name': 'Manufacturing Products Product Label',
    'version': '15.1.1.2',
    'category': 'product',
    'price': 15,
    'currency': 'EUR',
    "sequence": 1,
    "author" : "MAISOLUTIONSLLC",
    "email": 'apps@maisolutionsllc.com',
    "website":'http://maisolutionsllc.com/',
    'license': 'OPL-1', 
    'summary': 'Using this module you can print product lable for Manufacturing Product',
    'depends': ['base','web', 'mrp', 'product_expiry'],
    'data': [
        'security/ir.model.access.csv',
        'views/res_company_view.xml',
        'views/product_views.xml',
        'views/mrp_production_views.xml',
        'report/product_label_templates.xml',
        'report/product_label.xml',
    ],
    'demo': [],
    'images': ['static/description/main_screenshot.png'],
    'installable': True,
    'auto_install': False,
    'application': False,
}
